using System.Threading.Tasks;
using Xunit;

namespace Bitcraft.StateMachine.UnitTests.AutoGenerated
{
    partial class TestAutoUpdateState
    {
        protected override void OnEnter(StateEnterEventArgs e)
        {
            base.OnEnter(e);

            var context = (StateMachineTestContext)Context;

            Assert.Equal(2, context.TestStatus);
            context.TestStatus++;
        }

        private Task<HandlerResult> OnTestAutoTerminateAction(object _)
        {
            return Task.FromResult(new HandlerResult(TestAutoStateTokens.End));
        }

        private Task<HandlerResult> OnTestAutoUpdateAction(object _)
        {
            return Task.FromResult(new HandlerResult(TestAutoStateTokens.Update));
        }

        protected override void OnExit(StateExitEventArgs e)
        {
            base.OnExit(e);

            var context = (StateMachineTestContext)Context;

            Assert.Equal(3, context.TestStatus);
            context.TestStatus++;
        }
    }
}
