using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Bitcraft.StateMachine;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Bitcraft.StateMachine.UnitTests.AutoGenerated
{
    partial class TestAutoBeginState
    {
        protected override void OnEnter(StateEnterEventArgs e)
        {
            base.OnEnter(e);

            var context = (StateMachineTestContext)Context;

            Assert.AreEqual(context.TestStatus, 0);
            context.TestStatus++;
        }

        private void OnTestAutoInitDoneAction(object data, Action<StateToken> callback)
        {
            callback(TestAutoStateTokens.Update);
        }

        protected override void OnExit(StateExitEventArgs e)
        {
            base.OnExit(e);

            var context = (StateMachineTestContext)Context;

            Assert.AreEqual(context.TestStatus, 1);
            context.TestStatus++;
        }
    }
}
