using System.Threading.Tasks;
using Xunit;

namespace Bitcraft.StateMachine.UnitTests.AutoGenerated
{
    partial class TestAutoBeginState
    {
        protected override void OnEnter(StateEnterEventArgs e)
        {
            base.OnEnter(e);

            var context = (StateMachineTestContext)Context;

            Assert.Equal(0, context.TestStatus);
            context.TestStatus++;
        }

        private Task<HandlerResult> OnTestAutoInitDoneAction(object data)
        {
            return Task.FromResult(new HandlerResult(TestAutoStateTokens.Update));
        }

        protected override void OnExit(StateExitEventArgs e)
        {
            base.OnExit(e);

            var context = (StateMachineTestContext)Context;

            Assert.Equal(1, context.TestStatus);
            context.TestStatus++;
        }
    }
}
