/*
 ###########################################################
 ### Warning: this file has been generated automatically ###
 ###                    DO NOT MODIFY                    ###
 ###########################################################
*/

using System;
using Bitcraft.StateMachine;

namespace Bitcraft.StateMachine.UnitTests.AutoGenerated
{
    public partial class TestAutoUpdateState : TestAutoStateBase
    {
        public TestAutoUpdateState()
            : base(TestAutoStateTokens.Update)
        {
        }

        protected override void OnInitialized()
        {
            base.OnInitialized();
            RegisterActionHandler(TestAutoActionTokens.Terminate, OnTestAutoTerminateAction);
            RegisterActionHandler(TestAutoActionTokens.Update, OnTestAutoUpdateAction);
        }

        /*
        private void OnTestAutoTerminateAction(IStateData data, Action<StateToken> callback)
        {
            callback(TestAutoStateTokens.End);
        }

        private void OnTestAutoUpdateAction(IStateData data, Action<StateToken> callback)
        {
            callback(TestAutoStateTokens.Update);
        }
        */
    }
}
