/*
 ###########################################################
 ### Warning: this file has been generated automatically ###
 ###                    DO NOT MODIFY                    ###
 ###########################################################
*/

using System;
using Bitcraft.StateMachine;

namespace Bitcraft.StateMachine.UnitTests.AutoGenerated
{
    public partial class TestAutoEndState : TestAutoStateBase
    {
        public TestAutoEndState()
            : base(TestAutoStateTokens.End)
        {
        }

        protected override void OnInitialized()
        {
            base.OnInitialized();
            RegisterActionHandler(TestAutoActionTokens.Finalize, OnTestAutoFinalizeAction);
        }

        /*
        private void OnTestAutoFinalizeAction(IStateData data, Action<StateToken> callback)
        {
            callback(null);
        }
        */
    }
}
