/*
 ###########################################################
 ### Warning: this file has been generated automatically ###
 ###                    DO NOT MODIFY                    ###
 ###########################################################
*/

using System;
using Bitcraft.StateMachine;

namespace Bitcraft.StateMachine.UnitTests.AutoGenerated
{
    public partial class TestAutoBeginState : TestAutoStateBase
    {
        public TestAutoBeginState()
            : base(TestAutoStateTokens.Begin)
        {
        }

        protected override void OnInitialized()
        {
            base.OnInitialized();
            RegisterActionHandler(TestAutoActionTokens.InitDone, OnTestAutoInitDoneAction);
        }

        /*
        private void OnTestAutoInitDoneAction(IStateData data, Action<StateToken> callback)
        {
            callback(TestAutoStateTokens.Update);
        }
        */
    }
}
