set PATH="..\..\..\..\Tools\Bitcraft.StateMachineTool\bin\Debug"
set EXEC="%PATH%\Bitcraft.StateMachineTool.exe"

%EXEC% -file ./TestAuto.graphml -ns Bitcraft.StateMachine.UnitTests.AutoGenerated

pause
