/*
 ###########################################################
 ### Warning: this file has been generated automatically ###
 ###                    DO NOT MODIFY                    ###
 ###########################################################
*/

using System;
using Bitcraft.StateMachine;

namespace Bitcraft.StateMachine.UnitTests.AutoGenerated
{
    public partial class TestAutoStateMachine : StateManager
    {
        public TestAutoStateMachine()
            : this(null)
        {
        }

        public TestAutoStateMachine(object context)
            : base(context)
        {
            PreHandlersRegistration();

            RegisterState(new TestAutoBeginState());
            RegisterState(new TestAutoUpdateState());
            RegisterState(new TestAutoEndState());

            PostHandlersRegistration();

            SetInitialState(TestAutoStateTokens.Begin);
        }

        partial void PreHandlersRegistration();
        partial void PostHandlersRegistration();
    }
}
