/*
 ###########################################################
 ### Warning: this file has been generated automatically ###
 ###                    DO NOT MODIFY                    ###
 ###########################################################
*/

using System;
using Bitcraft.StateMachine;

namespace Bitcraft.StateMachine.UnitTests.AutoGenerated
{
    public static class TestAutoStateTokens
    {
        public static readonly StateToken Begin = new StateToken("Begin");
        public static readonly StateToken Update = new StateToken("Update");
        public static readonly StateToken End = new StateToken("End");

        public static readonly StateToken[] Items = 
        {
            Begin,
            Update,
            End
        };
    }
}
