/*
 ###########################################################
 ### Warning: this file has been generated automatically ###
 ###                    DO NOT MODIFY                    ###
 ###########################################################
*/

using System;
using Bitcraft.StateMachine;

namespace Bitcraft.StateMachine.UnitTests.AutoGenerated
{
    public static class TestAutoActionTokens
    {
        public static readonly ActionToken InitDone = new ActionToken("InitDone");
        public static readonly ActionToken Terminate = new ActionToken("Terminate");
        public static readonly ActionToken Update = new ActionToken("Update");
        public static readonly ActionToken Finalize = new ActionToken("Finalize");

        public static readonly ActionToken[] Items = 
        {
            InitDone,
            Terminate,
            Update,
            Finalize
        };
    }
}
